// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi.proto

package grpcapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRequest) Reset()         { *m = CallRequest{} }
func (m *CallRequest) String() string { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()    {}
func (*CallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{0}
}

func (m *CallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRequest.Unmarshal(m, b)
}
func (m *CallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRequest.Marshal(b, m, deterministic)
}
func (m *CallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRequest.Merge(m, src)
}
func (m *CallRequest) XXX_Size() int {
	return xxx_messageInfo_CallRequest.Size(m)
}
func (m *CallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallRequest proto.InternalMessageInfo

func (m *CallRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *CallRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CallResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{1}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CallResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *CallResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShutdownRequest struct {
	Clientid             string   `protobuf:"bytes,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{2}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

func (m *ShutdownRequest) GetClientid() string {
	if m != nil {
		return m.Clientid
	}
	return ""
}

type ShutdownResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{3}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func (m *ShutdownResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CallRequest)(nil), "grpcapi.CallRequest")
	proto.RegisterType((*CallResponse)(nil), "grpcapi.CallResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "grpcapi.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "grpcapi.ShutdownResponse")
}

func init() { proto.RegisterFile("grpcapi.proto", fileDescriptor_a7b78476b7b33751) }

var fileDescriptor_a7b78476b7b33751 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xa9, 0x1b, 0x5d, 0x77, 0xdc, 0x70, 0x1c, 0x74, 0xd4, 0x5e, 0x8d, 0x5e, 0x0d, 0xc1,
	0x5d, 0xd8, 0x07, 0x90, 0xb1, 0x0b, 0xef, 0x44, 0xa2, 0x2f, 0x50, 0xd3, 0xc3, 0x2c, 0x74, 0x6d,
	0xcc, 0x49, 0xf0, 0x09, 0x7c, 0x6f, 0x59, 0x96, 0xd4, 0x51, 0x76, 0x77, 0xfe, 0xe4, 0xfc, 0x7f,
	0xbe, 0xfc, 0x30, 0xdf, 0x6b, 0x25, 0x4b, 0x55, 0x6f, 0x94, 0xee, 0x4c, 0x87, 0x13, 0x2f, 0xf3,
	0x02, 0xae, 0x77, 0x65, 0xd3, 0x08, 0xfa, 0xb6, 0xc4, 0x06, 0x17, 0x30, 0x92, 0x87, 0x2a, 0x8d,
	0x56, 0xd1, 0x7a, 0x2a, 0x8e, 0x23, 0x22, 0x8c, 0xab, 0xd2, 0x94, 0xe9, 0xd5, 0x2a, 0x5a, 0xcf,
	0x84, 0x9b, 0xf3, 0x0f, 0x98, 0x9d, 0x4c, 0xac, 0xba, 0x96, 0x09, 0x53, 0x98, 0xb0, 0x95, 0x92,
	0x98, 0x9d, 0x33, 0x11, 0x41, 0xe2, 0x12, 0x62, 0xd2, 0xfa, 0xc0, 0x7b, 0xe7, 0x9f, 0x0a, 0xaf,
	0xfa, 0xd4, 0xd1, 0x59, 0xea, 0x23, 0xdc, 0xbc, 0x7f, 0x59, 0x53, 0x75, 0x3f, 0x6d, 0xc0, 0xc9,
	0x20, 0x91, 0x4d, 0x4d, 0xad, 0xa9, 0x03, 0x53, 0xaf, 0xf3, 0x07, 0x58, 0xfc, 0xaf, 0x7b, 0x90,
	0x25, 0xc4, 0x9a, 0xd8, 0x36, 0xc6, 0x73, 0x78, 0xf5, 0xf4, 0x1b, 0xc1, 0xfc, 0x45, 0xbc, 0xed,
	0x5e, 0xc9, 0x6c, 0x95, 0xda, 0xaa, 0x1a, 0x0b, 0x18, 0x1f, 0xbf, 0x80, 0xb7, 0x9b, 0x50, 0xcc,
	0x59, 0x0d, 0xd9, 0xdd, 0xe0, 0xd4, 0xc7, 0x3f, 0x43, 0x12, 0x9e, 0xc4, 0xb4, 0x5f, 0x19, 0x40,
	0x67, 0xf7, 0x17, 0x6e, 0x4e, 0x01, 0x9f, 0xb1, 0x6b, 0xbf, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x22, 0x50, 0x78, 0x0e, 0x8e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GRPCNetAppApiClient is the client API for GRPCNetAppApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCNetAppApiClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type gRPCNetAppApiClient struct {
	cc *grpc.ClientConn
}

func NewGRPCNetAppApiClient(cc *grpc.ClientConn) GRPCNetAppApiClient {
	return &gRPCNetAppApiClient{cc}
}

func (c *gRPCNetAppApiClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.GRPCNetAppApi/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCNetAppApiClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.GRPCNetAppApi/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCNetAppApiServer is the server API for GRPCNetAppApi service.
type GRPCNetAppApiServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

func RegisterGRPCNetAppApiServer(s *grpc.Server, srv GRPCNetAppApiServer) {
	s.RegisterService(&_GRPCNetAppApi_serviceDesc, srv)
}

func _GRPCNetAppApi_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCNetAppApiServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.GRPCNetAppApi/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCNetAppApiServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCNetAppApi_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCNetAppApiServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.GRPCNetAppApi/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCNetAppApiServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCNetAppApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.GRPCNetAppApi",
	HandlerType: (*GRPCNetAppApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GRPCNetAppApi_Call_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _GRPCNetAppApi_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi.proto",
}
